### ISSUE TITLE
enable GitHub page in this repo

### ISSUE THREAD

**Issue by PooiaFerdowsi** [irws/web-school-books#8]
from the setting menu on the left bar click on the pages option

this web site have difference with iran-web-school.github.io

**Comment by KomeilParseh** [comment]
Hello, the website is published in the following link.
<http://web-school.ir/>

**Comment by PooiaFerdowsi** [comment]
so can you add this domain in the repo description

**Comment by AshkanLaei** [comment]
> so can you add this domain in the repo description

Done.
